train:
  _target_: src.datasets.LibrispeechDataset
  part: "train-other-500"
  max_audio_length: 20.0
  max_text_length: 500
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.LibrispeechDataset
  part: "dev-other"
  max_audio_length: 20.0
  max_text_length: 500
  instance_transforms: ${transforms.instance_transforms.inference}
