# _target_: src.model.Conformer
# n_feats: 128
# fc_hidden: 512
# num_blocks: 16  # Number of Conformer blocks
# d_model: 256  # Dimension of model embeddings
# n_heads: 8  # Number of attention heads
# kernel_size: 32  # Kernel size for convolution module
# ff_expansion_factor: 4  # Expansion factor in feed-forward module
# conv_expansion_factor: 2  # Expansion factor in convolution module
# dropout: 0.1  # Dropout rate
# num_classes: 29  # Number of output classes
_target_: src.model.deepspeech.DeepSpeech
# input_dim: 5
# hidden_dim: 16
# num_gru_layers: 3
# num_classes: 29
# dropout: 0.1
input_dim: 80
hidden_dim: 256
num_gru_layers: 3
num_classes: 29
dropout: 0.1