defaults:
  - model: conformer
  - metrics: example
  - datasets: example1inf
  - dataloader: example
  - transforms: example
  - _self_
inferencer:
  device_tensors: ["audio", "spectrogram", "text_encoded", "text_encoded_length", "spectrogram_length"]
  device: cuda
  save_path: "example"
  seed: 1
  from_pretrained: "saved/model_best.pth"
  dataset_path: "ex.flac"
model:
  _target_: src.model.conformer.Conformer
  num_blocks: 16  # Number of Conformer blocks
  d_model: 256  # Dimension of model embeddings
  n_heads: 8  # Number of attention heads
  kernel_size: 32  # Kernel size for convolution module
  ff_expansion_factor: 4  # Expansion factor in feed-forward module
  conv_expansion_factor: 2  # Expansion factor in convolution module
  dropout: 0.1  # Dropout rate
  # num_classes: 29  # Number of output classes
  num_classes: 28
text_encoder:
  _target_: src.text_encoder.CTCTextEncoder
